/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mapfScenario_picat_PicatWrapper */

#ifndef _Included_mapfScenario_picat_PicatWrapper
#define _Included_mapfScenario_picat_PicatWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mapfScenario_picat_PicatWrapper
 * Method:    callPicatMain
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_mapfScenario_picat_PicatWrapper_callPicatMain
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
